### ISSUE TITLE
WebResponseStream Left Open

### ISSUE THREAD

**Issue by nkranes** [akamai-open/NetStorageKit-C-Sharp#1]
NetStorage.execute() returns a Stream to most methods without closing the Stream and merely returning a bool.  I am calling Upload() repetitively and the method succeeds only 2 times and then hangs, I assume waiting for the Streams to be closed.

I think, for example:

        public bool Delete(string path)
        {
            execute("POST", path, new APIParams() { Action ="delete" });
            return true;
        }

needs to be:

        public bool Delete(string path)
        {
            using (execute("POST", path, new APIParams() { Action ="delete" })) { }
            return true;
        }

**Comment by colinbendell** [comment]
Ack! Just realized I hadn't pushed my commit. Done.
